include: package:very_good_analysis/analysis_options.10.0.0.yaml
analyzer:
  errors:
    avoid_catches_without_on_clauses: ignore
    avoid_equals_and_hash_code_on_mutable_classes: ignore
    library_private_types_in_public_api: ignore
    public_member_api_docs: ignore
    use_to_and_as_if_applicable: ignore
