name: funx
description: Composable function decorators for advanced execution control and reliability.
version: 1.4.1
repository: https://github.com/makjac/funx
homepage: https://makjac.github.io/funx/

environment:
  sdk: ^3.9.2

dev_dependencies:
  markdown: ^7.3.1
  path: ^1.9.1
  test: ^1.25.6
  very_good_analysis: ^10.0.0

topics:
  - functional-programming
  - decorators
  - async
  - concurrency
  - utilities
